name: "🛠️ Request New Feature"
description: "Let us know what we should add."
labels: ["feature request"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe what you'd like. Mockups or screenshots are encouraged."
  - type: dropdown
    id: category
    attributes:
      label: "What type of change is this?"
      options:
        - "New Feature"
        - "Enhancement"
        - "Content"
        - "Docs"
        - "Other"
  - type: textarea
    id: references
    attributes:
      label: "Any links or references we should review?"
